version: '3.8'

services:
  node-app:
    build: ./node-app
    ports:
      - "3000:3000"
    volumes:
      - ./node-app:/app
      - /app/node_modules

    depends_on:
      - mongo
    environment:
      - NODE_ENV=development

  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
